// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type CreatePlaylistInput struct {
	Title    string `json:"title"`
	Public   bool   `json:"public"`
	TrackIDs []int  `json:"trackIDs"`
}

type CreatePlaylistSourceInput struct {
	PlaylistID int `json:"playlistID"`
	TrackID    int `json:"trackID"`
}

type CreateTrackInput struct {
	Title     string          `json:"title"`
	Sound     graphql.Upload  `json:"sound"`
	Thumbnail *graphql.Upload `json:"thumbnail"`
}

type CreateUserInput struct {
	UID         string `json:"uid"`
	DisplayName string `json:"displayName"`
}

type DeletePlaylistInput struct {
	ID int `json:"id"`
}

type DeletePlaylistSourceInput struct {
	PlaylistID int   `json:"playlistID"`
	TrackIDs   []int `json:"trackIDs"`
}

type UpdateTrackInput struct {
	Title     string          `json:"title"`
	Sound     *graphql.Upload `json:"sound"`
	Thumbnail *graphql.Upload `json:"thumbnail"`
}

type UpdateUserInput struct {
	Icon         *graphql.Upload `json:"icon"`
	Cover        *graphql.Upload `json:"cover"`
	DisplayName  *string         `json:"displayName"`
	WebURL       *string         `json:"webUrl"`
	Twitter      *string         `json:"twitter"`
	SoundCloud   *string         `json:"soundCloud"`
	Facebook     *string         `json:"facebook"`
	Youtube      *string         `json:"youtube"`
	Instagram    *string         `json:"instagram"`
	Introduction *string         `json:"introduction"`
}
