// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type CreateTrackInput struct {
	Title     string          `json:"title"`
	Sound     graphql.Upload  `json:"sound"`
	Thumbnail *graphql.Upload `json:"thumbnail"`
}

type CreateUserInput struct {
	UID         string `json:"uid"`
	DisplayName string `json:"displayName"`
}

type UpdateTrackInput struct {
	Title     string          `json:"title"`
	Sound     *graphql.Upload `json:"sound"`
	Thumbnail *graphql.Upload `json:"thumbnail"`
}

type UpdateUserInput struct {
	Icon         *graphql.Upload `json:"icon"`
	Cover        *graphql.Upload `json:"cover"`
	DisplayName  *string         `json:"displayName"`
	WebURL       *string         `json:"webUrl"`
	Twitter      *string         `json:"twitter"`
	SoundCloud   *string         `json:"soundCloud"`
	Facebook     *string         `json:"facebook"`
	Youtube      *string         `json:"youtube"`
	Instagram    *string         `json:"instagram"`
	Introduction *string         `json:"introduction"`
}
