// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type CreateTrackInput struct {
	Title          string          `json:"title"`
	ThumbnailImage *graphql.Upload `json:"thumbnailImage"`
}

type CreateUserInput struct {
	UID         string `json:"uid"`
	DisplayName string `json:"displayName"`
}

type UpdateTrackInput struct {
	Title          string          `json:"title"`
	ThumbnailImage *graphql.Upload `json:"thumbnailImage"`
}

type UpdateUserInput struct {
	IconImage    *graphql.Upload `json:"iconImage"`
	CoverImage   *graphql.Upload `json:"coverImage"`
	DisplayName  *string         `json:"displayName"`
	WebURL       *string         `json:"webUrl"`
	Introduction *string         `json:"introduction"`
}
