name: Deploy

on: 
  push:
    branches:
      - main

env:
  IMAGE: ${{ secrets.GCP_HOST }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }}:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Use gcloud CLI
        run: gcloud info

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet

      - name: Build
        run: docker build --target prod -t $IMAGE .

      - name: Push
        run: docker push $IMAGE

      - name: Deploy
        id: deploy-service
        uses: google-github-actions/deploy-cloudrun@v0.1.0
        with:
          image: $IMAGE
          service: ${{ secrets.GCP_SERVICE_NAME }}
          project: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}