name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }}-server:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure
        run: gcloud auth configure-docker --quiet

      - name: Build
        run: docker build --target prod -t $IMAGE .

      - name: Push
        run: docker push $IMAGE

      - name: Deploy
        run: |
            gcloud run deploy $SERVICE_NAME \
              --image $IMAGE \
              --project $GCP_PROJECT_ID \
              --region $GCP_REGION \
              --platform managed \
              --quiet