name: Migrate

on:
  push:
    branches: [ main ]

env:
  SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  IMAGE: migrate:${{ github.sha }}
  GCP_CLOUD_SQL_INSTANCE: ${{ secrets.GCP_PROJECT_ID }}:${{ secrets.GCP_REGION }}:${{ secrets.GCP_SERVICE_NAME }}=tcp:3306
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build
        run: docker build -t $IMAGE -f Dockerfile.migrate .

      - name: Get Cloud SQL Proxy
        run: |
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy

      - name: Connect to Cloud SQL
        run: |
          ./cloud_sql_proxy -instances=$GCP_CLOUD_SQL_INSTANCE
      
      - name: Migrate run
        run: |
          docker run -e DATABASE_URL=$DATABASE_URL $IMAGE
